#pragma once

#define CT_HEALTH 1100
#define CT_DAMAGE 300
#define CT_CRIT_DAMAGE 400
#define CT_MOVE_SPEED 10
#define CT_RANGE 300
#define CT_AUTOATTACK_SPEED 6
#define CT_SPEC1_COOLDOWN 60
#define CT_SPEC2_COOLDOWN 80
#define CT_ROCKET_SIZE 50
#define CT_ROCKET_DAMAGE 400
#define CT_ROCKET_MOVE_SPEED 25
#define CT_ROCKET_TIME 10 
#define CT_TRAP_SIZE 50
#define CT_TRAP_DAMAGE 200
#define CT_TRAP_MOVE_SPEED 0
#define CT_TRAP_TIME 1000
