#pragma once

#define IL_HEALTH 3000 
#define IL_DAMAGE 100
#define IL_MOVE_SPEED 9
#define IL_RANGE 0
#define IL_AUTOATTACK_SPEED 8
#define IL_SPEC1_COOLDOWN 70
#define IL_SPEC2_COOLDOWN 110
#define IL_FROZE_TIME 30
#define IL_TENTACLE_DAMAGE 200
