#pragma once

#define SH_HEALTH 2500 
#define SH_DAMAGE 150
#define SH_MOVE_SPEED 12
#define SH_RANGE 0
#define SH_AUTOATTACK_SPEED 8
#define SH_SPEC1_COOLDOWN 70
#define SH_SPEC2_COOLDOWN 60
#define SH_SHURIKEN_SIZE 20
#define SH_SHURIKEN_DAMAGE 250
#define SH_SHURIKEN_MOVE_SPEED 20
#define SH_SHURIKEN_TIME 9
